### ISSUE TITLE
Example does not work out of the box

### ISSUE THREAD

**Issue by mnpenner** [c4milo/node-inotify#43]
When I run your example exactly, I get this error:

```
var inotify = new Inotify(); //persistent by default, new Inotify(false) //no 
              ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/mbayazit/grunt-autodeploy/chok.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

I tried installing it both from `npm` and via `git`.

Running just this `console.log(require('inotify'));` returns an empty object `{}`.

Tested on Ubuntu.

**Comment by c4milo** [comment]
This doesn't seem to be an issue anymore. Closing.
