### ISSUE TITLE
Installation Error on Mac

### ISSUE THREAD

**Issue by angelathewebdev** [c4milo/node-inotify#51]
I've encountered the following error during installation. I'm running npm 2.5.1 on OSX 10.10

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'inotify' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ 'inotify', null ]
6 verbose cache add spec inotify
7 silly cache add parsed spec { raw: 'inotify',
7 silly cache add   scope: null,
7 silly cache add   name: 'inotify',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed inotify@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'inotify', range: '*', hasData: false }
12 silly mapToRegistry name inotify
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/inotify
16 verbose addNameRange registry:https://registry.npmjs.org/inotify not in flight; fetching
17 verbose request uri https://registry.npmjs.org/inotify
18 verbose request no auth needed
19 info attempt registry request try #1 at 15:25:57
20 verbose request id 70914ccc163312de
21 verbose etag "1TTYMECKK1TEJXSHL9RPZNKRZ"
22 http request GET https://registry.npmjs.org/inotify
23 http 200 https://registry.npmjs.org/inotify
24 silly get cb [ 200,
24 silly get   { date: 'Thu, 05 Mar 2015 07:25:58 GMT',
24 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"39-cd0a9e0275f515f8c1648ed73f21e3a4"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=60',
24 silly get     'content-length': '22923',
24 silly get     'accept-ranges': 'bytes',
24 silly get     via: '1.1 varnish',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-nrt6132-NRT',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1425540358.114764,VS0,VE209',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose get saving inotify to /Users/angelawang/.npm/registry.npmjs.org/inotify/.cache.json
26 silly addNameRange number 2 { name: 'inotify', range: '*', hasData: true }
27 silly addNameRange versions [ 'inotify',
27 silly addNameRange   [ '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.1.4',
27 silly addNameRange     '0.1.5',
27 silly addNameRange     '0.1.6',
27 silly addNameRange     '0.1.7',
27 silly addNameRange     '0.1.8',
27 silly addNameRange     '0.2.0',
27 silly addNameRange     '0.2.1',
27 silly addNameRange     '0.2.2',
27 silly addNameRange     '1.0.0',
27 silly addNameRange     '1.1.0',
27 silly addNameRange     '1.2.0',
27 silly addNameRange     '1.2.1' ] ]
28 verbose addNamed inotify@1.2.1
29 silly addNamed semver.valid 1.2.1
30 silly addNamed semver.validRange 1.2.1
31 silly cache afterAdd inotify@1.2.1
32 verbose afterAdd /Users/angelawang/.npm/inotify/1.2.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/angelawang/.npm/inotify/1.2.1/package/package.json written
34 silly install resolved [ { name: 'inotify',
34 silly install resolved     version: '1.2.1',
34 silly install resolved     author: { name: 'Camilo Aguilar', email: 'camilo@cloudescape.com' },
34 silly install resolved     email: 'camilo@cloudescape.com',
34 silly install resolved     keywords:
34 silly install resolved      [ 'inotify',
34 silly install resolved        'watch',
34 silly install resolved        'monitor',
34 silly install resolved        'watch files',
34 silly install resolved        'watch directories' ],
34 silly install resolved     description: 'inotify bindings for v8 javascript engine',
34 silly install resolved     repository: { type: 'git', url: 'http://github.com/c4milo/node-inotify' },
34 silly install resolved     engines: { node: '>=0.8' },
34 silly install resolved     main: 'inotify',
34 silly install resolved     scripts: { install: 'node-gyp rebuild' },
34 silly install resolved     gypfile: true,
34 silly install resolved     contributors: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
34 silly install resolved     _id: 'inotify@1.2.1',
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'dd3465d3739998cdfb1f1d5b0a38ca51478dfc32',
34 silly install resolved        tarball: 'http://registry.npmjs.org/inotify/-/inotify-1.2.1.tgz' },
34 silly install resolved     _from: 'inotify@*',
34 silly install resolved     _npmVersion: '1.2.14',
34 silly install resolved     _npmUser: { name: 'c4milo', email: 'camilo.aguilar@gmail.com' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     directories: {},
34 silly install resolved     _shasum: 'dd3465d3739998cdfb1f1d5b0a38ca51478dfc32',
34 silly install resolved     _resolved: 'https://registry.npmjs.org/inotify/-/inotify-1.2.1.tgz',
34 silly install resolved     bugs: { url: 'https://github.com/c4milo/node-inotify/issues' },
34 silly install resolved     readme: 'ERROR: No README data found!',
34 silly install resolved     homepage: 'https://github.com/c4milo/node-inotify' } ]
35 info install inotify@1.2.1 into /private/var/www/vue-hackernews
36 info installOne inotify@1.2.1
37 verbose installOne of inotify to /private/var/www/vue-hackernews not in flight; installing
38 verbose lock using /Users/angelawang/.npm/_locks/inotify-a49081cb22806c8a.lock for /private/var/www/vue-hackernews/node_modules/inotify
39 silly install write writing inotify 1.2.1 to /private/var/www/vue-hackernews/node_modules/inotify
40 silly cache addNamed cb inotify@1.2.1
41 verbose unbuild node_modules/inotify
42 verbose gentlyRm vacuuming /private/var/www/vue-hackernews/node_modules/inotify
43 verbose tar unpack /Users/angelawang/.npm/inotify/1.2.1/package.tgz
44 verbose tar unpacking to /private/var/www/vue-hackernews/node_modules/inotify
45 verbose gentlyRm vacuuming /private/var/www/vue-hackernews/node_modules/inotify
46 silly gunzTarPerm modes [ '755', '644' ]
47 silly gunzTarPerm extractEntry package.json
48 silly gunzTarPerm extractEntry .npmignore
49 silly gunzTarPerm extractEntry README.md
50 silly gunzTarPerm extractEntry LICENSE
51 silly gunzTarPerm extractEntry example.js
52 silly gunzTarPerm extractEntry inotify.js
53 silly gunzTarPerm extractEntry AUTHORS
54 silly gunzTarPerm extractEntry binding.gyp
55 silly gunzTarPerm extractEntry src/bindings.cc
56 silly gunzTarPerm extractEntry src/bindings.h
57 silly gunzTarPerm extractEntry src/node_inotify.cc
58 silly gunzTarPerm extractEntry src/node_inotify.h
59 info preinstall inotify@1.2.1
60 silly install resolved []
61 verbose about to build /private/var/www/vue-hackernews/node_modules/inotify
62 info build /private/var/www/vue-hackernews/node_modules/inotify
63 verbose linkStuff [ false,
63 verbose linkStuff   false,
63 verbose linkStuff   false,
63 verbose linkStuff   '/private/var/www/vue-hackernews/node_modules' ]
64 info linkStuff inotify@1.2.1
65 verbose linkBins inotify@1.2.1
66 verbose linkMans inotify@1.2.1
67 verbose rebuildBundles inotify@1.2.1
68 info install inotify@1.2.1
69 verbose unsafe-perm in lifecycle true
70 info inotify@1.2.1 Failed to exec install script
71 verbose unlock done using /Users/angelawang/.npm/_locks/inotify-a49081cb22806c8a.lock for /private/var/www/vue-hackernews/node_modules/inotify
72 verbose stack Error: inotify@1.2.1 install: `node-gyp rebuild`
72 verbose stack Exit status 1
72 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
72 verbose stack     at EventEmitter.emit (events.js:110:17)
72 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
72 verbose stack     at ChildProcess.emit (events.js:110:17)
72 verbose stack     at maybeClose (child_process.js:1008:16)
72 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
73 verbose pkgid inotify@1.2.1
74 verbose cwd /private/var/www/vue-hackernews
75 error Darwin 14.1.0
76 error argv "node" "/usr/local/bin/npm" "install" "inotify"
77 error node v0.12.0
78 error npm  v2.5.1
79 error code ELIFECYCLE
80 error inotify@1.2.1 install: `node-gyp rebuild`
80 error Exit status 1
81 error Failed at the inotify@1.2.1 install script 'node-gyp rebuild'.
81 error This is most likely a problem with the inotify package,
81 error not with npm itself.
81 error Tell the author that this fails on your system:
81 error     node-gyp rebuild
81 error You can get their info via:
81 error     npm owner ls inotify
81 error There is likely additional logging output above.
82 verbose exit [ 1, true ]
83 verbose unbuild node_modules/inotify
84 info preuninstall inotify@1.2.1
85 info uninstall inotify@1.2.1
86 verbose unbuild rmStuff inotify@1.2.1 from /private/var/www/vue-hackernews/node_modules
87 info postuninstall inotify@1.2.1
88 verbose gentlyRm vacuuming /private/var/www/vue-hackernews/node_modules/inotify
89 silly gentlyRm purging /private/var/www/vue-hackernews/node_modules/inotify
90 silly gentlyRm removing /private/var/www/vue-hackernews/node_modules
91 silly gentlyRm finished vacuuming up to /private/var/www/vue-hackernews
```

**Comment by c4milo** [comment]
@angelathewebdev inotify is a library inside the linux kernel. This module is not going to work on Mac.
