### ISSUE TITLE
npm version upgrade for node v0.8 testing

### ISSUE THREAD

**Issue by pogilvie** [c4milo/node-inotify#58]
I recently submitted a pull request for a branch which adds explicit nan scoping for v8 exceptions as newer v8 implementations require a V8::Isolate context to hold thread state.  Use of the deprecated interfaces without an Isolate context generate an annoying compiler warning on newer node implementations.  Since node is singled threaded the default Isolate context works fine and the Nan wrapper library handles this.

After I submitted my pull request travis reported that the build was failing.   So I hooked up travis and installed nvm (very handy!) and found that my suggested changes compile and execute example.js fine on node v0.8.

Looking more closely at the travis log files I saw that the error in the node v0.8 case was coming out of npm not the complier.   I don't think that my changes are introducing the build error but rather the error was latent in the travis test environment and triggered by my pull request .

```
The command "eval npm install " failed. 

module.js:340
    throw err;
      ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
   at Object.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
   at Module._compile (module.js:449:26)
   at Object.Module._extensions..js (module.js:467:10)"nan": "^2.0.5"
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:362:17)
```

I tested this suspicion with a hack to package.json c changing nan version description from "nan": "^2.0.5" to "nan": ">=2.05".    Build works fine with the backward compatible npm syntax.

Suggestion on how to proceed welcome!    

Best Regards,
Peter

**Comment by c4milo** [comment]
This should be fixed in v1.4.6
