### ISSUE TITLE
build error is Node 10.4.1

### ISSUE THREAD

**Issue by amit777** [c4milo/node-inotify#69]
```
> inotify@1.4.2 install /home/nodeuser/scratch/node_modules/inotify
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/nodeuser/scratch/node_modules/inotify/build'
  CXX(target) Release/obj.target/inotify/src/bindings.o
../src/bindings.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NodeInotify::Inotify::AddWatch(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/bindings.cc:172:46: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated (declared at /home/nodeuser/.node-gyp/10.4.1/include/node/v8.h:2845): Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value path(args_->Get(path_sym));
                                              ^
../src/bindings.cc: In static member function ‘static void NodeInotify::Inotify::Callback(uv_poll_t*, int, int)’:
../src/bindings.cc:279:34: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1596) [-Wdeprecated-declarations]
     callback.Call(handle, 1, argv);
                                  ^
  CXX(target) Release/obj.target/inotify/src/node_inotify.o
../src/node_inotify.cc: In function ‘void NodeInotify::InitializeInotify(v8::Handle<v8::Object>)’:
../src/node_inotify.cc:13:60: error: no matching function for call to ‘v8::ObjectTemplate::New()’
         Local<ObjectTemplate> global = ObjectTemplate::New();
                                                            ^
../src/node_inotify.cc:13:60: note: candidates are:
In file included from /home/nodeuser/.node-gyp/10.4.1/include/node/node.h:63:0,
                 from ../src/node_inotify.h:5,
                 from ../src/bindings.h:4,
                 from ../src/node_inotify.cc:2:
/home/nodeuser/.node-gyp/10.4.1/include/node/v8.h:5819:32: note: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(
                                ^
/home/nodeuser/.node-gyp/10.4.1/include/node/v8.h:5819:32: note:   candidate expects 2 arguments, 0 provided
/home/nodeuser/.node-gyp/10.4.1/include/node/v8.h:6026:32: note: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::internal::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(internal::Isolate* isolate,
                                ^
/home/nodeuser/.node-gyp/10.4.1/include/node/v8.h:6026:32: note:   candidate expects 2 arguments, 0 provided
make: *** [Release/obj.target/inotify/src/node_inotify.o] Error 1
make: Leaving directory `/home/nodeuser/scratch/node_modules/inotify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeuser/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 3.10.0-693.11.6.el7.x86_64
gyp ERR! command "/home/nodeuser/.nvm/versions/node/v10.4.1/bin/node" "/home/nodeuser/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeuser/scratch/node_modules/inotify
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN eslint-plugin-react@6.10.3 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inotify@1.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inotify@1.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by zWaR** [comment]
@c4milo Any chance a new release with this fix could be published?

**Comment by c4milo** [comment]
@zWaR yes! I will release a new version later today. Thanks for the reminder!

**Comment by zWaR** [comment]
@c4milo Wow, that's great. And thanks for the immediate response!

**Comment by c4milo** [comment]
1.4.6 should be up in NPM with this patch. I tested it against latest Node 10, 11, 8, 6 and 4.

**Comment by zWaR** [comment]
@c4milo Tested and it looks good! Thanks!
